version: '3.8'

services:
  database:
    container_name: database
    image: ${MYSQL_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
  php:
    container_name: php
    env_file:
      - .env
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ${PROJECT_PATH}:/var/www/symfony_docker
    depends_on:
      - database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
    ports:
      - ${PHPMYADMIN_PORT}:80
    links:
      - database:${MYSQL_SERVER}
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${PROJECT_PATH}:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database